baseURL: "https://kbs.murarisumit.in/"
author: 
languageCode: "en-us"
title: "knowledge base"
description: "My knowledge base, place where my tils and bookmarks reside"
paginate: 20
theme: "hugonews"

taxonomies:
  tag: "tags"
  category: "category"
  site: "sites"
  year: "year"
  month: "month"
  author: "author"

contentDir: "content"
enableGitInfo: true


pygmentsStyle: "vs"
#pygmentsStyle: "monokai"
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsOptions: "linenos=true,tabWidth=2"
params:
  email: "email@murarisumit.in"
  custom_css: 
    - "css/override.css"