baseURL: "https://kbs.murarisumit.in/"
title: "knowledge base"
description: "My knowledge base, place where my tils and bookmarks reside"
 
paginate: 20
theme: "hugonews"
defaultContentLanguage: en
languageCode: "en-us"

permalinks:
  /: :section/:slug
  
languages:
  en:
    params:
      title: "knowledge base en"
      description: "My knowledge base, place where my tils and bookmarks reside"


taxonomies:
  tag: "tags"
  category: "category"
  site: "sites"
  year: "year"
  month: "month"
  author: "author"

contentDir: "content"
enableGitInfo: true

pygmentsStyle: "vs"
#pygmentsStyle: "monokai"
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsOptions: "linenos=true,tabWidth=2"

enableEmoji: true
params:
  author: "murarisumit"
  email: "email@murarisumit.in"
  description: "My knowledge base, place where my tils and bookmarks reside"
  custom_css: 
    - "css/override.css"
  social:
    twitter: true
    hackernews: true
    email: true