baseURL: "https://www.yinyangi.in/kbs"
languageCode: "en-us"
title: "Tils and bookmarks"
description: "My knowledge base, place where my tils and bookmarks reside"
paginate: 30
theme: "hugonews"

taxonomies:
  tag: "tags"
  category: "category"
  site: "sites"

contentDir: "content"

pygmentsStyle: "vs"
#pygmentsStyle: "monokai"
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsOptions: "linenos=true,tabWidth=2"

